development:
  adapter: mysql2
  encoding: utf8
  database: industrydata
  pool: 5
  username: root
  password: asd
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: industrydata
  pool: 5
  username: tbs
  password: 2cwZAK
  host: iwomdata.mysql.rds.aliyuncs.com
